### ISSUE TITLE
What are the required fields for Grafana SQL query to work as dataRef input? 

### ISSUE THREAD

**Issue by simonasmulevicius-humbility** [andymchugh/andrewbmchugh-flow-panel#104]
I know that some plugins require specific field names (like `time` or `value`). So I wonder how you pass information from SQL time series query to Flow diagram?

For example, in panel.yml I have:

```
cellIdPreamble: "cell-"
cells:
  example_server:
    dataRef: "mydataseries"
```

So I thought that having Grafana Query with the same name will do the job:
![image](https://github.com/user-attachments/assets/c9b509ff-7d4c-4395-9c64-2e2c1455a07f)

But I am probably missing something...
