### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by RafaelAybar** [andymchugh/andrewbmchugh-flow-panel#124]
Hi, I would like to clarify how can I use my own prometheus querys in the SVG that you provide as example.

Not sure if this could help, but I can do a small .gif once the example works.

Thanks for your time!

**Comment by andymchugh** [comment]
you start with a working example. i.e. example 1 svg and yaml. You add your prometheus query to the panel. You press on the Data button under debugging to see how your query is being presented to the panel. You change one of the dataRefs in the example yaml to the name your Prometheus query data comes in as.

It's the same process regardless of what your datasource is.

**Comment by RafaelAybar** [comment]
So, a dataRef could be a Grafana Variable? Something like `$time_series?`

**Comment by andymchugh** [comment]
no, a dataRef is the name given to the time-series produced by your prometheus query.

Your first step, always when dealing with datasources is to develop your query in a timeseries panel. The timeseries names on the legend in that panel are likely the names you should be putting into dataRef. So get your query working in a timeseries panel, then add it to your flow panel.

When you write a prometheus query (or any query), there are buttons at the top of the grafana pane where you write it to issue the request and see the returned result. That should give you a clue as to what your query is returning. If you go one step further and press the panel Debugging -> Data button in the Flow panel, your console will print out what dataframes have been received. You should see the example test data alongside your data.

**Comment by RafaelAybar** [comment]
So, I still have several questions. Not sure about what I am understanding wrong, but:
1. If I have 1 single box, correctly mapped, what I need to configure then?
![Screenshot from 2024-11-04 15-25-13](https://github.com/user-attachments/assets/83c6d847-f68f-424a-9a53-d11075075c31)
Maybe do I need to do some transformation to the Prometheus query?

My configPanel:
```YAML

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"


#------------------------------------------------------------------------------
# Panel Config
background:
  darkThemeColor: "yellow"
  lightThemeColor: "green"
cellIdPreamble: "cell-"
cells:
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
  docs:
    link:
      url: "https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/src/README.md"
  sxlDJdj_Db1evZtNV29t-1:
    dataRef: "A"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      dataRef: "A"
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
    link: *grafana-home
```
