### ISSUE TITLE
draw.io release 26.0.x breaks functionality 

### ISSUE THREAD

**Issue by FloSch62** [andymchugh/andrewbmchugh-flow-panel#127]
### Issue Description
After upgrading to draw.io 26.0.4, threshold-based styling (fill colors and stroke colors) no longer works in Grafana Flow Panel. The elements are not getting updated visually, although the data mapping appears correct in the debug console.

### Expected Behavior
- Elements should update their fill colors and stroke colors based on threshold configurations
- Visual updates should reflect the mapped data values

### Current Behavior
- Elements remain static and do not change colors
- Debug console shows correct data mapping
- No visual updates are applied to the diagram elements

### Steps to Reproduce
1. Configure a Flow Panel with threshold-based styling
2. Use YAML configuration similar to:
```yaml
anchors:
  thresholds-operstate:
    - color: red
      level: 0
    - color: green
      level: 1
cells:
  port1:
    dataRef: oper-state:ixr1:1/1/1
    fillColor:
      thresholds: *thresholds-operstate
```

3. Observe that elements do not update their styling

### Environment
draw.io version: 26.0.4
Platform: Desktop and Web versions
Grafana Flow Panel version: latest
Grafana version: latest

### Additional Information
Issue is not present in draw.io 25.x and lower versions
Affects both desktop and web versions of draw.io 26.0.x
