### ISSUE TITLE
fillColor fills all shape and not background only

### ISSUE THREAD

**Issue by Ahrlan** [andymchugh/andrewbmchugh-flow-panel#133]
Hi,

First of all, thanks for this amazing plugin I discovered few weeks ago.
I had no issue until today using it but I think last update changed some "fillColor" parameters.

You can see on the graph below that I have somes L3 switches shapes, Firewalls and cloud with a simple test "ping UP/DOWN", and the fillColor parameter change the shapes from green to red.

![Image](https://github.com/user-attachments/assets/66ddaa16-5b05-499d-940f-ff9c91c11e6f)

Today, even if I didn't touch my Grafana visualization, all the shapes are now filled with a first plan square with the good color.
I don't see what kind of device it is anymore

![Image](https://github.com/user-attachments/assets/431c186e-e07e-4a89-a9dd-da018235d135)

My panelConfig is pretty simple : 

``` 
---
anchorLinks:
  - thresholds: &status-tresholds
    - {color: "red", level: 0}
    - {color: "green", level: 1}

cellIdPreamble: "cell-"
cells:
  internet:
    dataRef: "status-internet"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  router1:
    dataRef: "status-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw1:
    dataRef: "status-sw1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
```
 
If needed, I can share as much as information as possible about my issue.
The queries and data work fine, it's all about aesthetic.

Best Regards,
Clément

**Comment by andymchugh** [comment]
Can you paste a copy of your svg here that goes with the above yaml? I need to see the actual document to be able to troubleshoot it.

**Comment by Ahrlan** [comment]
Thanks for the quick answer.
Below you can find the SVG and the full YAML file.
Draw.io is 26.0.4

![Image](https://github.com/user-attachments/assets/2cd85e56-4cfd-4060-9a57-1f94bc51f0ac)

```
---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - thresholds: &status-tresholds
    - {color: "red", level: 0}
    - {color: "green", level: 1}

cellColorMappings:
  darkTheme:
    red: "light-red"
    orange: "light-orange"
    green: "light-green"
  lightTheme:
    red: "red"
    orange: "orange"
    green: "green"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells:
  internet:
    dataRef: "status-internet"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  fw1:
    dataRef: "status-fw1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  fw2:
    dataRef: "status-fw2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  router1:
    dataRef: "status-router"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  router2:
    dataRef: "status-router"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw1:
    dataRef: "status-sw1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw2:
    dataRef: "status-sw2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw3:
    dataRef: "status-sw3"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw4:
    dataRef: "status-sw4"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  sw5:
    dataRef: "status-sw5"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-internet-router1:
    dataRef: "status-link-internet-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-internet-router2:
    dataRef: "status-link-internet-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-fw1-router1:
    dataRef: "status-link-fw1-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-fw1-router2:
    dataRef: "status-link-fw1-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-fw2-router1:
    dataRef: "status-link-fw2-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-fw2-router2:
    dataRef: "status-link-fw2-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-fw-failover:
    dataRef: "status-link-fw-failover"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-router-vss1:
    dataRef: "status-link-router-vss1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-router-vss2:
    dataRef: "status-link-router-vss2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw1-router1:
    dataRef: "status-link-sw1-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw1-router2:
    dataRef: "status-link-sw1-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw2-router1:
    dataRef: "status-link-sw2-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw2-router2:
    dataRef: "status-link-sw2-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw3-router1:
    dataRef: "status-link-sw3-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw3-router2:
    dataRef: "status-link-sw3-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw4-router1:
    dataRef: "status-link-sw4-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw4-router2:
    dataRef: "status-link-sw4-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw5-router1:
    dataRef: "status-link-sw5-router1"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
  link-sw5-router2:
    dataRef: "status-link-sw5-router2"
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
```

**Comment by Ahrlan** [comment]
I think I know the issue, I used "Export as > Advanced > SVG" to create my file instead of "Export as > SVG".
I didn't want my file to be a xxx.drawio.svg but I did use draw.io to generate the file.
Here you can find the file that could be open directly from draw.io

![Image](https://github.com/user-attachments/assets/6ad1ebd1-2548-409a-8050-fa8f4a6ca32d)

I'll try your fix but it seems it's pretty annoying yo work directly on the svg file.
I'll also see if some other shapes could work properly with the template. As I said, template works fine, it's only aesthetic and if I need to use other shapes it's no big deal

**Comment by andymchugh** [comment]
thanks for that. I'll see what I can do. It would be great to support it.

**Comment by Ahrlan** [comment]
Just for you to know, I tried to use other shapes in a new draw.io file and it worked fine.
It really depends on the shape used.

If needed you can close the issue as we found the problem and it's not really from your side.

Regards,
Clément

**Comment by andymchugh** [comment]
Thanks, that's good news. I'll keep it open for the moment though. It would be nice to offer some support for these interesting widgets. I'll play around with it for a bit.

**Comment by RandGH** [comment]
I am not so sure that the shape is the culprit.
I have a similar problem where on a new (very basic) diagram things work fine with a rectangle (in my case fill and label coloring), but when i use similar formatting it in a multi level diagram (circle over rectangle over rectangle), only the fill works - i don't see any text in it (neither black not colorized)...

I'll try to provide a sample diagram

**Comment by andymchugh** [comment]
@RandGH This issue is about the driving of the style-fill attribute since version 1.17. Your problem doesn't sound related. If you still have a problem can you raise it as a separate issue but with the following changes:

- The svg and yaml should just contain the smallest amount of stuff to demonstrate the problem.
- The yaml must be correctly formatted. All the indentation in the above is gone. You can do that by surrounding it in three backticks, like my svg snippet further up.
- The yaml should ideally use test-data like all the example that are given.
- the problem you are seeing should be as simple as you can make it.

If you do all of that I can just copy/paste it over and see what you are seeing. I appreciate you've gone to a lot of effort to provide all the above, but it's not giving me a workable starting point.

Looking at what you have done, I'd say your problem is you are trying to do too much in one go. If you test as you add each new shape and feature you'll immediately see the problem and you'll be best placed to fix it. Have a look through the getting-started docs and the FAQ there. You mention above that you are expecting to see text but in the SVG that you've posted there is no text. You have to explicitly add text to your diagram if you expect to be able to drive it.

Hope that helps.

**Comment by andymchugh** [comment]
@Ahrlan I've added a new yaml term 'fillColorElementFilter' which provides a way for people to filter how fillColor will be applied. With your 'L3 switch' example, you can now drive just the background by adding this term to your yaml. i.e.

```
  link-fw1-router1:
    dataRef: "status-link-fw1-router1"
    fillColorElementFilter: [{name: "rect"}]
    fillColor:
      gradientMode: "hue"
      thresholds: *status-tresholds
```
It's described under 'Fill Filter' in the [Feature Exploration](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/complexShapes.svg) section.

It's built into 17.1. I'll close this out once that's published.
