### ISSUE TITLE
Tags not hiding some elements (connector edges and Images)

### ISSUE THREAD

**Issue by joaofilipedg** [andymchugh/andrewbmchugh-flow-panel#145]
First of all, @andymchugh great job on amazing work done with this plugin. It allows the creation of some pretty awesome things.

I was trying to design a flow that would hide some of the paths depending on the selected tags. I was able to achieve most of the things I intended to, but unfortunately still couldn't find out a way to hide two things: 
* The inside of the connectors edge
* Images

![Image](https://github.com/user-attachments/assets/239d8202-b93c-4de7-8186-1c577f3b3cc6)

I figured the way to show/hide the connectors was to define their strokeColor in the panel-config, but this does not hide the fill of the edge of that connector. Unfortunately, this also can't be solved by defining the fillColor, since that really would mess up the connector.

On the other hand, I also couldn't find a way to hide the simple logo image. fillColor and strokeColor didn't work in this case.

Is this fixable by some way I am not figuring out?

Here is a reproducible example: 
![SVG](https://github.com/user-attachments/assets/ca11413b-2412-4a39-b5c1-4f3990cd18c6)
```yaml
---
  
anchorLinks:
  - flowAnimation: &flow-slow
      thresholdOffValue: 0
      thresholdLwrValue: 10
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 80
      thresholdUprDurationSecs: 0.1
  - thresholdIDPs: &threshold-idps
      - {color: "green", level: 0}
      - {color: "orange", level: 250}
      - {color: "red", level: 500}

tagConfig:
  legend: ["|", "IDPs:", "ORCID 1", "ORCID 2", "|"]
  color: "red"
  highlightRgbFactor: 1.0
  lowlightAlphaFactor: 0.0

cellIdPreamble: "cell-"
gradientMode: "hue"

cells: 
  orcid1:
    dataRef: "test-data-small-cos"
    fillColor:
      thresholds: *threshold-idps
    fillColorElementFilter: [{name: "path"}]
    labelColor:
      thresholds: *threshold-idps
    tags: ["All", "ORCID 1"]
  line_orcid1:
    dataRef: "test-data-small-cos"
    flowAnimation: *flow-slow
    strokeColor: 
      thresholds:
        - {color: "semi-dark-blue", level: 0}
    tags: ["All", "ORCID 1"]
  auths_orcid1:
    dataRef: "test-data-small-cos"
    label:
      separator: "replace"
      units: "none"
      decimalPoints: 0
      valueMappings:
        - {value: null, text: "0"}
    labelColor:
      thresholds: *threshold-idps
    tags: ["All", "ORCID 1"]
  orcid2:
    dataRef: "test-data-large-cos"
    fillColor:
      thresholds: *threshold-idps
    fillColorElementFilter: [{name: "path"}]
    labelColor:
      thresholds: *threshold-idps
    tags: ["All", "ORCID 2"]
  line_orcid2:
    dataRef: "test-data-large-cos"
    flowAnimation: *flow-slow
    strokeColor: 
      thresholds:
        - {color: "semi-dark-blue", level: 0}
    tags: ["All", "ORCID 2"]
  auths_orcid2:
    dataRef: "test-data-large-cos"
    label:
      separator: "replace"
      units: "none"
      decimalPoints: 0
      valueMappings:
        - {value: null, text: "0"}
    labelColor:
      thresholds: *threshold-idps
    tags: ["All", "ORCID 2"]
  ```
