### ISSUE TITLE
Some shapes from Draw.io dont fill when mapped in the plugin

### ISSUE THREAD

**Issue by jammiemil** [andymchugh/andrewbmchugh-flow-panel#27]
Abit of a wierd one this. Some of the basic shapes in Draw.io will happily accept labels but they break/disapear if you try to fill them in the plugin.

For Example:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/b601d130-e78f-4ddc-80a1-4275a9760a86)

Top row are all 'basic' shapes, second row are all 'Double' equivelents of the basic shapes (filed under Misc)

If i pull them into the plugin they render fine:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/275085d4-92fd-49d1-8587-728c1e04049c)

But as soon as i add panel config that referances them the top row disapears and only the bottom row gets filled:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/6a995654-914a-45a0-b078-fb1b083d16e6)

The panel config here is targetting all the cell id's and using the same data series to make them all the same color, so i should have two rows of Red shapes here.

Heres the Draw.io svg:

 ![Untitled Diagram drawio](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/81faa1d3-8c5c-4b7c-9d75-956496b40987)

and the panel config:

<details>

```

---
#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells:
  Rectangle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Double Rectangle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "red", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Rounded Rectangle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Double Rounded Rectangle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "red", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Elipse:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Double Elipse:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "red", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Square:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Double Square:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "red", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Circle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
  Double Circle:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: "celsius"
      decimalPoints: 1
    labelColor:
      thresholds:
        - { color: "blue", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }
    fillColor:
      thresholds:
        - { color: "red", level: 0 }
        - { color: "orange", level: 15 }
        - { color: "red", level: 20 }

```

 </details>
