### ISSUE TITLE
PromQL query are exposed as `undefined`

### ISSUE THREAD

**Issue by basvdl** [andymchugh/andrewbmchugh-flow-panel#5]
Any PromQL query will be exposed as `undefined`. Renaming the query or setting the legend will not help.

The only working combination is to set `dataRef` to `undefined`. Tested on Grafana Cloud v11.0.0-67746 (5f6bf93dd5)

<img width="709" alt="image" src="https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/123811/a1220720-1f1c-49f4-a914-c2fc2af3f118">

<img width="1067" alt="image" src="https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/123811/769fad5f-d7f3-4967-b7b1-27fbd6e74ce1">

<img width="742" alt="image" src="https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/123811/15cb5883-5a68-4dea-84c9-bd66db3404d5">

panel.yaml
```
---
gradientMode: "hue"
cellIdPreamble: "cell-"
cells:
  boxtxt:
    dataRef: "undefined"
    label:
      separator: "colon"
      units: "pps"
      decimalPoints: 2
```
