### ISSUE TITLE
dataRef AliasTags

### ISSUE THREAD

**Issue by netforce** [andymchugh/andrewbmchugh-flow-panel#55]
We have been using the flowcharting plugin for quite some time, but now we want to switch to the flow plugin. 

We have a query with tags like 'host' and 'interface' to get measurements from influxdb, instead of doing a query per switch, per interface. But we are unable to reference the wanted tag on a Cell, because the dataRef only expects one result, with maybe a timeline. Not tagged results.

It would be a big inprovement when we can reference a tag after a 'dataRef', or select a tag after the dataRef.

example below;

```
cells:
 cell-one:
   dataRef: "Query-A-series:InterfaceTag"
```
Or to use a new yaml definition
```
cells:
 cell-one:
   dataRef: "Query-A-series"
   tag: "InterfaceTag"
```

Also within other defenitions in the yaml we would like to be able to use the tags defined in the query, like in URL's.

```
cells:
  cell-one:
  link:
    url: "https://grafana.com/interfaceDashboard?var-host=[[tag_host]]&var-port=[[tag_port]]"
```
