### ISSUE TITLE
Reverse the directions of positive & negative values in flowAnimations

### ISSUE THREAD

**Issue by yo8192** [andymchugh/andrewbmchugh-flow-panel#88]
I have an SVG arrow, with arrow heads on both ends, with the config:

```
    flowAnimation:
      thresholdOffValue: 10
      thresholdLwrValue: 100
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 3000
      thresholdUprDurationSecs: 0.1
      unidirectional: false
```

That ends up making the animation go:
* left to right for positive values
* right to left for positive values

Would it be possible to reverse this, so that:
* positive values makes it go right to left
* negative values makes it go left to right

I can do it by turning around the SVG arrow in my editor, but a `direction: normal` and `direction: reverse` in Flow Panel would be nicer if there isn't already a way to do it.

I tried putting negative values on the `thresholdLwrValue` and `thresholdUprValue` but that didn't seem to work.

**Comment by andymchugh** [comment]
When you select 'flow' in draw.io you get a particular direction so it should be clear what 'positive' flow represents. If your data has the opposite sign to what you want for poitive flow, you could flip it by creating a bespokeDataRef. i.e.
```
dataRef: "myDataRef"
bespokeDataRef: "reverseData"
bespoke:
  formulas:
    - "reverseData = -data[myDataRef]"
 ```

I appreciate that's more boilerplate but it sounds like the arrow is drawn incorrectly given the data you are feeding it. Not sure adding another yaml term is the way to go as each one makes things more complex. Does this bespokeDataRef approach give you what you need?

**Comment by andymchugh** [comment]
hmm, actually, just tried above bespoke and bespoke formulas won't run uness an attribute is being driven. i.e. you'd have to add a dummy drive.
```
      drives:
        - elementName: "path"
          elementPosition: 1
          attribsSet:
            visibility: "true"

```
That needs to be fixed...
