### ISSUE TITLE
label separator `replace` adds a newline?

### ISSUE THREAD

**Issue by yo8192** [andymchugh/andrewbmchugh-flow-panel#89]
In 1.16.1, it seems that label separator `replace` is adds a newline when it shouldn't?

The SVG in my editor (or if I open directly in my browser) looks like: 
![image](https://github.com/user-attachments/assets/f8a456e3-0b61-4984-9e2d-5794f188d50a)

As you can see the labels are too high, on top of the arrows, which I did for now as a work around.

I have config like this for my labels:
```
  BatteryDischargeLabel:
    dataRef: "Battery Discharge Power"
    label:
      separator: "replace"
      units: "watt"
      decimalPoints: 1
```

Which gives in in Grafana Flow Panel something like: 
![image](https://github.com/user-attachments/assets/fc74209c-cdb8-49ba-a82a-9aa6f161916c)

As you can see the labels are shifted down, I suspect because an extra newline char is there where it shouldn't.
