### ISSUE TITLE
Shape fill shape background instead of shape color, and black with missing data

### ISSUE THREAD

**Issue by bijwaard** [andymchugh/andrewbmchugh-flow-panel#9]
I added fillColor to the panel config, on the "DSO connection" on top left and inverters on the bottom. I expected the shape to be filled with the fillColor, but instead the background of the shape image gets filled with the color.

```
  DSO Generation:
    dataRef: "CT:sum-active"

    fillColor:
      gradientMode: "hue"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
``` 
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/977c5853-169f-4243-ba26-05c7acd24fa0)

The style of the shape is as follows:
`pointerEvents=1;verticalLabelPosition=bottom;shadow=0;dashed=0;align=center;fillColor=rgba(50, 172, 45, 0.97);html=1;verticalAlign=top;strokeWidth=1;shape=mxgraph.electrical.signal_sources.ac_source;strokeColor=#000000;fontColor=#000000;fontSize=14;fontStyle=1`

Furthermore, when data is missing, the shape background becomes black and all other labels are missing in the figure. I would rather use the last known data value, since not all data may always be nicely linked up.
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/177aae81-c3cc-408d-b248-96695734d328)

Kind regards,
Dennis

**Comment by bijwaard** [comment]
The shape fill does appear to work with the voltage shape, for this I now have site config:
```
---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance
thresholds:
  powerThresholds:
    - {color: "semi-dark-green", level: 0}
    - {color: "orange", level: 500}
    - {color: "red", level: 1000}
  voltageThresholds:
    - {color: "#semi-dark-green", level: 0}
    - {color: "orange", level: 245}
    - {color: "red", level: 250}

```
And panel config:
```
  VT:L1:
    dataRef: "VT:1"
    label:
      separator: "replace"
      units: "volt"
      decimalPoints: 1
    labelColor:
      gradientMode: "none"
      thresholdsRef: "voltageThresholds"
    fillColor:
      gradientMode: "hue"
      thresholdsRef: "voltageThresholds"
  VT:L2:
    dataRef: "VT:2"
    label:
      separator: "replace"
      units: "volt"
      decimalPoints: 1
    labelColor:
      gradientMode: "none"
      thresholdsRef: "voltageThresholds"
    fillColor:
      gradientMode: "hue"
      thresholdsRef: "voltageThresholds"
  VT:L3:
    dataRef: "VT:3"
    label:
      separator: "replace"
      units: "volt"
      decimalPoints: 1
    labelColor:
      gradientMode: "none"
      thresholdsRef: "voltageThresholds"
    fillColor:
      gradientMode: "none"
      thresholdsRef: "voltageThresholds"
```

The voltage panel looks like this, however I expected to see some semi-dark-green for voltage L1, L2, and L3, while L1 and L2 get orange and L3 gets black with gradientMode "None" (The L3 value is available though):
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/c90f3309-8554-4fb7-b406-217437dae2fa)
